# Generated by Django 5.2.8 on 2025-11-23 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphotoarray',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomphotoarray',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomphotoarray',
            name='user',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel_room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoArray',
        ),
        migrations.DeleteModel(
            name='RoomPhotoArray',
        ),
    ]
