# Generated by Django 5.2.8 on 2025-11-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_roomphotoarray_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
